### ISSUE TITLE
intermittent guzzle 401 Unauthorized

### ISSUE THREAD

**Issue by michael-lynch** [troydavisson/PHRETS#121]
When I try pulling down properties, it sometimes works flawlessly. Other times, it times out after a few minutes with this error:

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] http://myurl.com [status code] 401 [reason phrase] Unauthorized' in ../vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
```

I'm running some scripts after the properties are pulled down that take some time to process. Does the connection expire? Is this a Guzzle issue? I'm using `dev-master` in composer.

**Comment by liusqi** [comment]
I'm having the same issue here. My assumption is that the listings are probably sold/modified while I'm requesting, thus I don't have access to the listings and error is returned.

**Comment by michael-lynch** [comment]
Ah, I didn't think of that. That sounds plausible. I'm not sure how we could confirm that though.

I'm planning on setting up a cron job to hit a URL X amount of times per day that will pull down the properties. I guess if there is an error, it will automatically retry soon after, but I don't want to have to rely on that.

**Comment by brettbruce** [comment]
Im getting the same error, runs awhile and then:
401 Unauthorized` response:
Invalid or missing session. Use the login URL to login to this RETS server.
 in /Applications/MAMP/htdocs/Websites/crmlsConnector/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /Applications/MAMP/htdocs/Websites/crmlsConnector/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /Applications/MAMP/htdocs/Websites/crmlsConnector/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Applications/MAMP/htdocs/Websites/crmlsConnector/vendor/guzzlehttp in /Applications/MAMP/htdocs/Websites/crmlsConnector/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
