### ISSUE TITLE
ValueError: unconverted data remains: T00:00:00.000

### ISSUE THREAD

**Issue by aviivgi** [troydavisson/PHRETS#215]
When executing the following line (searching for listings):
```
    search_result = resource_class.search(query='(StatusChangeTimestamp=2018-09-04-2018-09-05)')
```

I get the following error:
```python
WARNING:root:UnexpectedError: <class 'ValueError'>
Traceback (most recent call last):
  File "rets_downloader_property_data_v3.0.py", line 179, in <module>
    search_result = resource_class.search(query='(StatusChangeTimestamp=2018-09-04-2018-09-05)')
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/resource_class.py", line 66, in search
    rows = decoder.decode(result.data)
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/decoder.py", line 34, in decode
    for row in rows)
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/decoder.py", line 34, in <genexpr>
    for row in rows)
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/decoder.py", line 33, in <genexpr>
    return tuple(OrderedDict((field, decode_field(field, value)) for field, value in row.items())
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/decoder.py", line 31, in decode_field
    return decoders[field](value)
  File "/Users/bigoper/GitHub/idx2.0/com.idx20.downloader.rets.python/rets/client/decoder.py", line 96, in <lambda>
    'Date': lambda value: datetime.strptime(value, '%Y-%m-%d'),
  File "/Users/bigoper/anaconda3/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/Users/bigoper/anaconda3/lib/python3.6/_strptime.py", line 365, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: T00:00:00.000

```

1. started 3 weeks ago
2. no recent code change

Thanks!

**Comment by troydavisson** [comment]
2 main things stand out to me:

1) That's Python, and this is an open source tool for PHP, so I think you're using a different lower-level library
2) The field you're searching is called `StatusChangeTimestamp` which suggests that the value should be a timestamp, not a date.  If you try `(StatusChangeTimestamp=2018-09-04T00:00:00-2018-09-05T00:00:00)` as your query, I suspect you'll have better results.
