### ISSUE TITLE
Query Error on Stellar MLS

### ISSUE THREAD

**Issue by vhcontrerasdeveloper** [troydavisson/PHRETS#242]
**Hi, help me please, can't resolve this problem. from Stellar MLS**

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://rets.stellarmls.com/rets/search?SearchType=Property&Class=Property&Query=%28ListingKeyNumeric%20%3D%200%2B%29&QueryType=DMQL2&Count=1&Format=COMPACT-DECODED&Limit=99999999&StandardNames=0` resulted in a `404 Not Found` response in /var/www/rets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/rets/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/rets/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/rets/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/rets/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/rets/vendor/guzzl in /var/www/rets/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by nader14y** [comment]
Hi, Use post method should be true for this feed.

**Comment by vhcontrerasdeveloper** [comment]
Hi, thanks for answering, how do I do that?

**Comment by tdan** [comment]
> Hi, thanks for answering, how do I do that?
You'll need to set use_post_method to true in config options

`$config->setOption('use_post_method', true); // boolean`
