### ISSUE TITLE
RETS Server: IP address failure

### ISSUE THREAD

**Issue by vseow** [troydavisson/PHRETS#246]
Hi there,

We're currently getting the following error when connecting to a Flexmls source from another instance:

```
PHP Fatal error:  Uncaught PHRETS\Exceptions\RETSException: RETS Server: IP address failure in /../vendor/troydavisson/phrets/src/Session.php:424
Stack trace:
#0 /../vendor/troydavisson/phrets/src/Session.php(76): PHRETS\Session->request('Login')
#1 /../file.php(38): PHRETS\Session->Login()
#2 /../file.php(9): callFunction()
#3 {main}
  thrown in /../vendor/troydavisson/phrets/src/Session.php on line 424
```

The IP is whitelisted but we're using a newer version of PHP (7.2 vs 5.6). 

Does anybody have any insight on this? Thank you so much

**Comment by uudruid74** [comment]
Any progress on this?  I'm using 7.1.17 on my test server, but 7.1.22 on the production server.   I get the same issue.   The production server is not under my control

**Comment by troydavisson** [comment]
Your RETS account has an IP filter on it that only allows certain servers
(yours) to talk to the Flexmls RETS server.  This error represents that
you're connecting to the Flexmls RETS server from a computer/server that
isn't whitelisted on your account.

**Comment by uudruid74** [comment]
According to the RETS provider, they have put the IP into the whitelist.  So, either php breaks something in 5 minor revisions, or the RETS provider is completely incompetent.

**Comment by uudruid74** [comment]
@troydavisson 

The provider has sent me a screenshot showing that the correct IP is in the system.  Any clue why I would still be getting this error??

**Comment by uudruid74** [comment]
Also, the return code from the Login request is 200 ... which should be a success.  How does PHRETS know this is an IP Address Failure?   I don't see how this is being communicated.   Could a change in PHP between 7.1.17 and 7.1.22 be the cause of a bug here?
