### ISSUE TITLE
How can inquiry using status 

### ISSUE THREAD

**Issue by vandupio** [troydavisson/PHRETS#282]
Hi Im new to the PHRETS but it have been very use full but I couldn't get a listing using Status active  
$search = $rets->Search("Property","RA_1","(Status=A)",['Limit'=>3]);

result
Stack trace:
#0 D:\xampp\htdocs\test\vendor\troydavisson\phrets\src\Session.php(280): PHRETS\Session->request('Search', Array)
#1 D:\xampp\htdocs\test\d.php(40): PHRETS\Session->Search('Property', 'RA_1', '(Status=A)', Array)
#2 {main}
  thrown in D:\xampp\htdocs\test\vendor\troydavisson\phrets\src\Session.php on line 427

**Comment by crkacer** [comment]
Search('Property', 'ResidentialProperty', "(Status=A)", [])
