### ISSUE TITLE
GetObject return Invalid header syntax error

### ISSUE THREAD

**Issue by san8work** [troydavisson/PHRETS#322]
In laravel
It working fine on some mls but some mls return error
Invalid header syntax

$photos = $rets->GetObject("Property", "Photo",'S6673582);

**Comment by aconital** [comment]
I'm getting the same error. This is the crash:

` Invalid header syntax #0 /var/www/api/vendor/guzzlehttp/psr7/src/Message.php(235): GuzzleHttp\Psr7\Message::parseMessage()
#1 /var/www/api/vendor/troydavisson/phrets/src/Parsers/GetObject/Multiple.php(52): GuzzleHttp\Psr7\Message::parseResponse()
#2 /var/www/api/vendor/troydavisson/phrets/src/Session.php(136): PHRETS\Parsers\GetObject\Multiple->parse()
#3 /var/www/api/app/Traits/ListingSyncTrait.php(1914): PHRETS\Session->GetObject()`

**Comment by aconital** [comment]
Update: I think I know what's going on. When "Description:" value has line break and is in multiline like the example I provided above:

```
Content-Type: image/jpeg
Content-ID: C7063702
Object-ID: 10
Description: QUARTZ COUNTERS MARBLE
BACKSPLASH

```
The code fails to parse. I tried removing the value and it worked. I added the following code to troydavisson/phrets/src/Parsers/GetObject/Multiple.php line 39

```
$fieldToUpdate = 'Description';
// Create a regular expression pattern to match the field and its value
$pattern = "/{$fieldToUpdate}:(.*?)(\r?\n\r?\n|$)/si";
// Use preg_replace to remove the value until an empty line is reached
$body = preg_replace($pattern, "{$fieldToUpdate}:\r\n\r\n", $body);
```

**Comment by aconital** [comment]
@troydavisson The PR is up if you are okay with the change 

https://github.com/troydavisson/PHRETS/pull/323
